apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-server.fullname" . }}-secrets
  labels:
    {{- include "vault-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  VAULT_DEV_ROOT_TOKEN_ID: {{ .Values.vault.devRootTokenId | quote }}
  secret.json: |-
    {
      "STRONG_PASSWORD": {{ .Values.secrets.STRONG_PASSWORD | quote }},
      "WEAK_PASSWORD": {{ .Values.secrets.WEAK_PASSWORD | quote }}
    }
