clusterDomain: "k8scluster"
clusterId: "4L6g3nShT-eMCtK--X86sw"

# Kafka Brokers (KRaft mode)
kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: "7.8.0"
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 10Gi
  resources:
    limits:
      cpu: 800m
      memory: 768Mi
    requests:
      cpu: 150m
      memory: 384Mi
  jvmOpts: "-Xms256m -Xmx256m"
  logDirs: "/var/lib/kafka/data"
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  nodes:
    - id: 1
      name: kafka-1-itp
      externalPort: 9092
      offsetsTopicReplicationFactor: 3
    - id: 2
      name: kafka-2-itp
      externalPort: 9094
      offsetsTopicReplicationFactor: 1
    - id: 3
      name: kafka-3-itp
      externalPort: 9096
      offsetsTopicReplicationFactor: 1

# Schema Registry
schemaRegistry:
  enabled: true
  name: schema-registry-itp
  image:
    repository: confluentinc/cp-schema-registry
    tag: "7.8.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  debug: "true"
  topic: "_schemas"
  replicationFactor: 3
  persistence:
    enabled: true
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 5Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

# Debezium Kafka Connect
debezium:
  enabled: true
  name: debezium-kafka-connect-itp
  image:
    repository: debezium-kafka-connect-itp
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083
  groupId: "cdc_connect-group"
  configStorageTopic: "cdc_connect_configs"
  offsetStorageTopic: "cdc_connect_offsets"
  statusStorageTopic: "cdc_connect_status"
  keyConverter: "io.confluent.connect.avro.AvroConverter"
  valueConverter: "io.confluent.connect.avro.AvroConverter"
  persistence:
    enabled: true
    storageClassName: ""
    accessMode: ReadWriteOnce
    pluginsSize: 5Gi
    dataSize: 5Gi
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi

# Kafka UI
kafkaUi:
  enabled: true
  name: kafka-ui-itp
  image:
    repository: provectuslabs/kafka-ui
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    nodePort: null
  auth:
    type: "LOGIN_FORM"
    username: "admin"
    password: "qwer"
  clusterName: "local"
  persistence:
    enabled: true
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 2Gi
  resources:
    limits:
      cpu: "1.0"
      memory: 2G
    requests:
      cpu: "0.5"
      memory: 1G
