clusterDomain: "k8scluster"
clusterId: "4L6g3nShT-eMCtK--X86sw"

# Kafka Brokers (KRaft mode)
kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: "7.8.0"
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClassName: "longhorn"
    accessMode: ReadWriteOnce
    size: 2Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  jvmOpts: "-Xms128m -Xmx256m"
  logDirs: "/var/lib/kafka/data"
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  nodes:
    - id: 1
      name: kafka-1-itp
      externalPort: 9092
      offsetsTopicReplicationFactor: 3
    - id: 2
      name: kafka-2-itp
      externalPort: 9094
      offsetsTopicReplicationFactor: 1
    - id: 3
      name: kafka-3-itp
      externalPort: 9096
      offsetsTopicReplicationFactor: 1

# Schema Registry
schemaRegistry:
  enabled: true
  name: schema-registry-itp
  image:
    repository: confluentinc/cp-schema-registry
    tag: "7.8.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  debug: "false"
  topic: "_schemas"
  replicationFactor: 3
  jvmOpts: "-Xms128m -Xmx256m"
  persistence:
    enabled: true
    storageClassName: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi
  resources:
    limits:
      cpu: 250m
      memory: 384Mi
    requests:
      cpu: 25m
      memory: 192Mi

# Debezium Kafka Connect
debezium:
  enabled: true
  name: debezium-kafka-connect-itp
  image:
    repository: quay.io/debezium/connect
    tag: "3.4.0.Final"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083
  groupId: "cdc_connect-group"
  configStorageTopic: "cdc_connect_configs"
  offsetStorageTopic: "cdc_connect_offsets"
  statusStorageTopic: "cdc_connect_status"
  keyConverter: "io.confluent.connect.avro.AvroConverter"
  valueConverter: "io.confluent.connect.avro.AvroConverter"
  jvmOpts: "-Xms128m -Xmx384m"
  persistence:
    enabled: true
    storageClassName: "longhorn"
    accessMode: ReadWriteOnce
    pluginsSize: 2Gi
    dataSize: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 384Mi

# Kafka UI
kafkaUi:
  enabled: true
  name: kafka-ui-itp
  image:
    repository: provectuslabs/kafka-ui
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    nodePort: null
  auth:
    type: "LOGIN_FORM"
    username: "admin"
    password: "qwer"
  clusterName: "local"
  jvmOpts: "-Xms64m -Xmx256m"
  persistence:
    enabled: true
    storageClassName: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi
  resources:
    limits:
      cpu: 250m
      memory: 384Mi
    requests:
      cpu: 25m
      memory: 128Mi
