{{- if .Values.microDb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microDb.name }}-secret
  labels:
    {{- include "itp-postgres.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.microDb.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.microDb.auth.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.microDb.auth.password | quote }}
{{- end }}
---
{{- if .Values.iamDb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.iamDb.name }}-secret
  labels:
    {{- include "itp-postgres.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.iamDb.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.iamDb.auth.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.iamDb.auth.password | quote }}
{{- end }}
