replicaCount: 1

image:
  repository: container-registry.oracle.com/database/enterprise
  tag: "19.3.0.0"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: oracle-registry-secret
  pullSecret:
    create: false
    name: "oracle-registry-secret"
    server: "container-registry.oracle.com"
    username: ""
    password: ""
    email: ""

nameOverride: ""
fullnameOverride: "oracle-itp"

serviceAccount:
  create: false
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 1521
  nodePort: null

oracle:
  pwd: "Oracle@168"
  enableArchiveLog: "true"

persistence:
  enabled: true
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 20Gi

resources:
  limits:
    cpu: 1000m
    memory: 2560Mi
  requests:
    cpu: 100m
    memory: 1536Mi

nodeSelector: {}
tolerations: []
affinity: {}
