apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oracle19c.fullname" . }}-init-scripts
  labels:
    {{- include "oracle19c.labels" . | nindent 4 }}
data:
  01_init_script.sql: |-
{{- if .Values.initScript }}
{{ .Values.initScript | indent 4 }}
{{- else }}
{{ .Files.Get "init_scripts/01_init_script.sql" | indent 4 }}
{{- end }}
