apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle19c.fullname" . }}-secret
  labels:
    {{- include "oracle19c.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORACLE_PWD: {{ .Values.oracle.pwd | quote }}
