apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle19c.fullname" . }}
  labels:
    {{- include "oracle19c.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1521
      protocol: TCP
      name: listener
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "oracle19c.selectorLabels" . | nindent 4 }}
